_BASE_: "base.yaml"
OUTPUT_DIR: "../out/detectron"
MODEL:
  WEIGHTS: "../out/detectron/model_final.pth"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128  # faster, and good enough for this toy dataset (default: 512)
    NUM_CLASSES: 3
    SCORE_THRESH_TEST: 0.5  # set the testing threshold for this model
DATASETS:
  TRAIN: ("instruments_train",)
  TEST: ("instruments_val",)
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 400001 # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
  BASE_LR: 0.00025 # pick a good LR
  IMS_PER_BATCH: 2

