_BASE_: "base.yaml"
OUTPUT_DIR: "../maskrcnn/output"
MODEL:
#   WEIGHTS: model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
#  WEIGHTS: "../out/detectron/model_final_old.pth"
#  WEIGHTS: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128  # faster, and good enough for this toy dataset (default: 512)
    NUM_CLASSES: 3
    SCORE_THRESH_TEST: 0.5  # set the testing threshold for this model
DATASETS:
  TRAIN: ("instruments_train",)
  TEST: ("instruments_val",)
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 1 # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
  BASE_LR: 0.00025 # pick a good LR
  IMS_PER_BATCH: 2

