_BASE_: "base.yaml"
OUTPUT_DIR: "../out/combined"
MODEL:
  DEVICE: "cpu"
  #   WEIGHTS: model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  WEIGHTS: "../out/combined/model_final.pth"
  #  WEIGHTS: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  ROI_HEADS:
    NUM_CLASSES: 3              # segmentation classes
  CSL_HEAD:
    LOCALISATION_CLASSES: 4     # localisation classes (obviously)
    LAMBDA: 1.                  # tradeoff parameter between segmentation and localisation (high: better loc, worse seg)
    SIGMA: 7                    # standard deviation for gaussian kernel applied to ground truth heatmaps
    POOLER_RESOLUTION: 7        # resolution of the first feature map, final resolution is: x * 2^4
    EVALUATION:
      EPSILON: 1e-6             # epsilon for the dice coefficient
DATASETS:
  TRAIN: ("instruments_train",)
  TEST: ("instruments_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER:  5
  BASE_LR: 0.00025
  IMS_PER_BATCH: 1

