_BASE_: "base.yaml"
OUTPUT_DIR: "../out/combined"
MODEL:
  DEVICE: "cpu"
  #   WEIGHTS: model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
  WEIGHTS: "../out/combined/model_final.pth"
  #  WEIGHTS: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  ROI_HEADS:
    NUM_CLASSES: 3              # segmentation classes
  CSL_HEAD:
    LAMBDA: 0.05                # tradeoff parameter between segmentation and localisation
    LOCALISATION_CLASSES: 4
    POOLER_RESOLUTION: 7        # resolution of the first feature map, final resolution is: x * 2^4
DATASETS:
  TRAIN: ("instruments_train",)
  TEST: ("instruments_val",)
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER:  5
  BASE_LR: 0.00025
  IMS_PER_BATCH: 1

